# Generated by Django 2.0.1 on 2018-02-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
