# Generated by Django 2.0.1 on 2018-02-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0002_auto_20180204_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
