# Generated by Django 2.0.1 on 2018-02-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0003_auto_20180204_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='title',
        ),
    ]
