# Generated by Django 2.0.1 on 2018-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0005_auto_20180204_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
