# Generated by Django 2.0.2 on 2018-03-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0006_auto_20180301_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='id_event',
        ),
    ]
