# Generated by Django 2.0.2 on 2018-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweegle', '0007_auto_20180305_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id_event',
            new_name='id',
        ),
    ]
